### ISSUE TITLE
Can't access to website

### ISSUE THREAD

**Issue by lyj0309** [2captcha/cloudflare-demo#1]
hi there
i just clone code and run the script, but it's cant open the webisite ,can't bypass the cf
the webiste is https://portal.ustraveldocs.com/scheduleappointment

**Comment by dzmitry-duboyski** [comment]
@lyj0309 On the site you specified, you get blocked by Cloudflare. This block is not related to the captcha, first of all you need to figure out what you need to do for not to get blocked by Cloudflare.
